// ==========================================
// Abo 3Asy ENGINE - V7.0
// ==========================================

// 1. تهيئة الزائر
function initVisitor() {
    let userId = localStorage.getItem('abuAssi_UserID');
        if (!userId) {
                userId = 'ID-' + Math.floor(Math.random() * 900000 + 100000);
                        localStorage.setItem('abuAssi_UserID', userId);
                            }
                                const display = document.getElementById('visitorDisplay');
                                    if(display) display.innerHTML = `Visitor: <span style="color:#fff">${userId}</span>`;
                                    }

                                    // 2. التحقق من المفاتيح
                                    let usedKeys = JSON.parse(localStorage.getItem('abuAssi_UsedKeys')) || [];

                                    function validateKey(inputKey, successCallback) {
                                        const msgBox = document.getElementById('msgBox');
                                            inputKey = inputKey.trim();

                                                if(!inputKey) {
                                                        msgBox.innerHTML = '<span style="color:gray">اكتب الكود أولاً!</span>';
                                                                return;
                                                                    }
                                                                        if (masterKeys.includes(inputKey)) {
                                                                                msgBox.innerHTML = '<span style="color:var(--gold)">👑 كود VIP مقبول!</span>';
                                                                                        setTimeout(successCallback, 1500);
                                                                                                return;
                                                                                                    }
                                                                                                        if (!oneTimeKeys.includes(inputKey)) {
                                                                                                                msgBox.innerHTML = '<span style="color:var(--danger)">❌ الكود غير صحيح!</span>';
                                                                                                                        return;
                                                                                                                            }
                                                                                                                                if (usedKeys.includes(inputKey)) {
                                                                                                                                        msgBox.innerHTML = '<span style="color:orange">⚠️ الكود مستخدم سابقاً!</span>';
                                                                                                                                                return;
                                                                                                                                                    }

                                                                                                                                                        usedKeys.push(inputKey);
                                                                                                                                                            localStorage.setItem('abuAssi_UsedKeys', JSON.stringify(usedKeys));
                                                                                                                                                                msgBox.innerHTML = '<span style="color:var(--primary)">✅ كود صحيح.. جاري فك التشفير...</span>';
                                                                                                                                                                    setTimeout(successCallback, 1500);
                                                                                                                                                                    }

                                                                                                                                                                    // 3. وظائف عامة
                                                                                                                                                                    function copyCode() {
                                                                                                                                                                        const code = document.getElementById('codeViewer').innerText;
                                                                                                                                                                            navigator.clipboard.writeText(code).then(() => alert('تم النسخ ✅'));
                                                                                                                                                                            }
                                                                                                                                                                            function closeModals() {
                                                                                                                                                                                document.querySelectorAll('.modal-overlay').forEach(m => m.style.display = 'none');
                                                                                                                                                                                }

                                                                                                                                                                                // 4. نظام الأدمن
                                                                                                                                                                                let generatedKey = '';
                                                                                                                                                                                function openAdminPanel() {
                                                                                                                                                                                    const modal = document.getElementById('adminAuthModal');
                                                                                                                                                                                        if(modal) {
                                                                                                                                                                                                modal.style.display = 'flex';
                                                                                                                                                                                                        document.getElementById('adminKeyInput').value = '';
                                                                                                                                                                                                                document.getElementById('adminMsg').innerHTML = '';
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                // إعادة تعيين أيقونة العين
                                                                                                                                                                                                                                        const input = document.getElementById("adminKeyInput");
                                                                                                                                                                                                                                                const icon = document.getElementById("toggleIcon");
                                                                                                                                                                                                                                                        if(input && icon) {
                                                                                                                                                                                                                                                                    input.type = "password";
                                                                                                                                                                                                                                                                                icon.classList.remove("fa-eye-slash");
                                                                                                                                                                                                                                                                                            icon.classList.add("fa-eye");
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                        function verifyAdmin() {
                                                                                                                                                                                                                                                                                                            const input = document.getElementById('adminKeyInput').value.trim();
                                                                                                                                                                                                                                                                                                                const msg = document.getElementById('adminMsg');

                                                                                                                                                                                                                                                                                                                    if(adminKeys.includes(input)) {
                                                                                                                                                                                                                                                                                                                            msg.innerHTML = '<span style="color:var(--primary)">✅ تمام يـ باشا</span>';
                                                                                                                                                                                                                                                                                                                                    const randomIndex = Math.floor(Math.random() * oneTimeKeys.length);
                                                                                                                                                                                                                                                                                                                                            generatedKey = oneTimeKeys[randomIndex];

                                                                                                                                                                                                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                document.getElementById('adminAuthModal').style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('genKeyDisplay').innerText = generatedKey;
                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('adminResultModal').style.display = 'flex';
                                                                                                                                                                                                                                                                                                                                                                                                }, 1000);
                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                            msg.innerHTML = '<span style="color:var(--danger)">❌ كود الأدمن خطأ!</span>';
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                function copyGeneratedKey() {
                                                                                                                                                                                                                                                                                                                                                                                                                    navigator.clipboard.writeText(generatedKey);
                                                                                                                                                                                                                                                                                                                                                                                                                        alert("تم نسخ المفتاح الجديد ✅");
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                        // 5. إظهار وإخفاء الباسورد (جديد)
                                                                                                                                                                                                                                                                                                                                                                                                                        function togglePasswordVisibility() {
                                                                                                                                                                                                                                                                                                                                                                                                                            const input = document.getElementById("adminKeyInput");
                                                                                                                                                                                                                                                                                                                                                                                                                                const icon = document.getElementById("toggleIcon");
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (input.type === "password") {
                                                                                                                                                                                                                                                                                                                                                                                                                                            input.type = "text";
                                                                                                                                                                                                                                                                                                                                                                                                                                                    icon.classList.remove("fa-eye");
                                                                                                                                                                                                                                                                                                                                                                                                                                                            icon.classList.add("fa-eye-slash");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        input.type = "password";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                icon.classList.remove("fa-eye-slash");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        icon.classList.add("fa-eye");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.onload = initVisitor;